baseURL = 'https://alinealcaraz.com.br/'
languageCode = 'pt-br'
title = 'Aline Alcaraz Murillo'
theme = 'hugo-elate-theme'

[params]
  
  custom_css = ["css/aline_style.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  googleMapsApiKey = "$HUGO_GOOGLE_MAPS_API_KEY"

  # Navigation
  [params.navigation]
    brand = "Aline Alcaraz Murillo"
    home = "Início"
    work = "Conheça a Aline"
    testimonials = "Testemunhos"
    services = "Áreas de Atuação"
    about = "Atendimento Sem Fronteiras"
    contact = "Contato"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "A assistência jurídica que você precisa em um escritório especializado no atendimento de mulheres."
    subtitle = '“Ninguém se empodera individualmente se o grupo não estiver empoderado.” (Joice Berth) - Sabemos que o meio jurídico, além de inacessível em muitos aspectos, é também ambiente de reprodução de muitas violências estruturais; infelizmente, não é incomum que mulheres, ao buscarem o abrigo da Lei e do Judiciário para suas demandas, se deparem com profissionais insensíveis às suas dores e incapazes de compreender a realidade de que partem. Por isso, nosso objetivo é atuar a partir das lentes de gênero, raça e classe a fim de ofertar um serviço acolhedor e de excelência para mulheres que desejam se ver livres e lutar pelos seus direitos e o de suas crias.'
    
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
    enable = false

  # Work section
  [params.work]
    enable = true
    title = "Conheça a Aline"
    description = "![avatar](/avatar.jpeg)\n\nAline Alcaraz Murillo, formada em 2011 pela Universidade São Judas Tadeu, é advogada desde 2012. Associada à Escola Brasileira de Direitos das Mulheres, possui ampla experiência na defesa de direitos de populações vulneráveis, tendo atuado como advogada em diferentes organizações não governamentais. Durante a graduação, integrou um grupo de estudos sobre justiça restaurativa e participou de duas formações (teórica e prática) em mediação de conflitos, tema que sempre lhe foi caro.  Militou na Pastoral da Juventude - organização vinculada à Igreja Católica do Brasil - na defesa de direitos da juventude, tendo colaborado com a Frente Parlamentar em Defesa dos Direitos da Juventude da ALESP. Desde 2021 é também mãe da Amélie e, a partir da experiência da maternagem em uma sociedade capitalista e patriarcal, decidiu voltar sua atuação profissional ao atendimento de outras mães/mulheres cuidadoras, em especial em matérias atinentes ao Direito das Famílias."
    #footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    #[[params.work.row]]
    #  img = "work_1.jpg"
    #  alt = "Image2"
    #  title = "Project 1"
    #  subtitle = "Branding"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    
  # Services section
  [params.services]
    enable = true
    title = "Áreas de atuação"
    description = "Veja, a título de exemplo, algumas das áreas de atuação e matérias atendidas pelo escritório. Se não tiver certeza de que atendemos sua demanda, entre em contato para confirmar! "

    [[params.services.item]]
      title = "DIREITO DAS FAMÍLIAS"
      description = "* Mediação extrajudicial\n* Divórcio\n* Reconhecimento e dissolução de união estável\n* Partilha de bens\n* Declaração (Investigação) de paternidade\n* Guarda e convivência (visitas) de filhos e plano parental\n* Alimentos\n* Tutela e curatela\n* Reconhecimento de maternidade e paternidade socioafetivas"
      icon = "icon-home"

    [[params.services.item]]
      title = "DIREITO DA CRIANÇA E DO ADOLESCENTE"
      description = "* Direito infracional (adolescentes acusados/as de ato infracional)\n* Direito à educação"
      icon = "icon-child"
    [[params.services.item]]
      title = "DIREITO DA CONSUMIDORA"
      description = "* Ações de indenização por danos materiais e morais"
      icon = "icon-bag"

      [[params.services.item]]
      title = "OUTRAS DEMANDAS CÍVEIS"
      description = ""      
      icon = "icon-plus"

  # About section
  [params.about]
    enable = true
    title = "Atendimento sem fronteiras"
    description = "Nós sabemos que o deslocamento dentro da cidade pode ser extremamente inconveniente para a rotina das mulheres e, especialmente, para as mulheres mães. Assim, diante das facilidades trazidas pelo processo eletrônico - onde até as audiências podem ser realizadas de maneira remota - optamos por implementar um *escritório virtual e sem fronteiras* o que, além de reduzir custos, nos permite oferecer nossos serviços para você que precisa de uma consultoria jurídica qualificada e deseja ser ouvida com empatia e respeito por uma advogada feminista, não importa em que estado do Brasil você esteja. Ainda assim, caso deseje, nossa base territorial é na cidade de São Paulo e estamos disponíveis para atendê-la enquanto tomamos um café <3"

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = false
    title = "FALE COMIGO"
    description = "Tenha contato direto com sua advogada e um atendimento personalizado às suas necessidades."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-whatsapp", "[(11) 92007-9706](https://wa.me/11920079706)"],
        ["icon-envelope", "alinealcaraz.adv@gmail.com"],
        ["icon-linkedin", "[Perfil Profissional](https://www.linkedin.com/in/alinealcaraz/)"]
      ]

    name = "Nome"
    email = "Email"
    phone = "Celular"
    message = "Mensagem"
    button = "Enviar mensagem"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]